<a href="https://colab.research.google.com/github/jiyeon-dcu/dcu-algorithms-2019/blob/master/%EC%A0%84%EA%B5%AD%EB%A7%A4%EB%A7%A4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
sample = files.upload()

Saving 2018-9~2020-9 월간 매매가격지수(변경후).xlsx to 2018-9~2020-9 월간 매매가격지수(변경후).xlsx

# 파일 불러오기

In [ ]:
df = pd.read_excel('2018-9~2020-9 월간 매매가격지수(변경후).xlsx') 
df

      지 역 2018년 09월 Unnamed: 2  ... Unnamed: 48 2020년 09월 Unnamed: 50
0     NaN        지수        변동률  ...         변동률        지수         변동률
1      전국   100.902       0.31  ...        0.47    104.42        0.42
2     수도권   102.818        0.7  ...        0.52     109.2        0.43
3     지방권    99.197      -0.04  ...        0.43   100.254        0.41
4   6대광역시   100.013       0.07  ...        0.38   104.705        0.53
5   5대광역시    100.04       0.09  ...        0.44   104.038        0.62
6     9개도    99.718       0.13  ...        0.44   102.105        0.38
7     8개도      98.6      -0.13  ...        0.26    97.236        0.21
8      서울   106.048       1.25  ...        0.42   110.419        0.27
9      경기   101.208       0.47  ...        0.68   108.743         0.6
10     인천    99.922       0.01  ...        0.19   106.975        0.21
11     부산    98.897      -0.13  ...        0.46    99.063        0.55
12     대구   102.275       0.36  ...        0.48   107.566        0.72
13     광주   102.403       0.67  ...        0.07   105.073         0.1
14     대전   100.902       0.18  ...        0.75   120.997        1.19
15     울산    95.288      -0.59  ...        0.43    93.094        0.61
16     세종   101.728       0.01  ...        7.69   134.368        3.83
17     강원    99.068       -0.1  ...        0.22    96.488         0.2
18     충북    98.195       -0.2  ...        0.12    96.849        0.06
19     충남    98.515      -0.03  ...        0.57     98.29        0.47
20     전북    99.904       0.07  ...        0.18     99.81        0.22
21     전남   101.642       0.28  ...        0.27   106.386         0.2
22     경북    98.536       -0.2  ...        0.32     96.13        0.24
23     경남    96.169      -0.51  ...         0.2    92.658        0.13
24     제주   100.737        0.2  ...        -0.1    96.393       -0.09

[25 rows x 51 columns]

In [ ]:
df1 = pd.read_excel('2018-9~2020-9 월간 매매가격지수(변경후).xlsx', header=1) # 컬럼을 0행으로 변경
df1

   Unnamed: 0       지수   변동률     지수.1  ...    지수.23  변동률.23    지수.24  변동률.24
0          전국  100.902  0.31  101.094  ...  103.980    0.47  104.420    0.42
1         수도권  102.818  0.70  103.247  ...  108.730    0.52  109.200    0.43
2         지방권   99.197 -0.04   99.181  ...   99.841    0.43  100.254    0.41
3       6대광역시  100.013  0.07  100.188  ...  104.156    0.38  104.705    0.53
4       5대광역시  100.040  0.09  100.220  ...  103.396    0.44  104.038    0.62
5         9개도   99.718  0.13   99.812  ...  101.720    0.44  102.105    0.38
6         8개도   98.600 -0.13   98.453  ...   97.035    0.26   97.236    0.21
7          서울  106.048  1.25  106.588  ...  110.119    0.42  110.419    0.27
8          경기  101.208  0.47  101.629  ...  108.098    0.68  108.743    0.60
9          인천   99.922  0.01  100.076  ...  106.746    0.19  106.975    0.21
10         부산   98.897 -0.13   98.812  ...   98.520    0.46   99.063    0.55
11         대구  102.275  0.36  102.848  ...  106.793    0.48  107.566    0.72
12         광주  102.403  0.67  103.028  ...  104.970    0.07  105.073    0.10
13         대전  100.902  0.18  101.474  ...  119.572    0.75  120.997    1.19
14         울산   95.288 -0.59   94.559  ...   92.533    0.43   93.094    0.61
15         세종  101.728  0.01  101.904  ...  129.413    7.69  134.368    3.83
16         강원   99.068 -0.10   98.881  ...   96.298    0.22   96.488    0.20
17         충북   98.195 -0.20   97.929  ...   96.787    0.12   96.849    0.06
18         충남   98.515 -0.03   98.349  ...   97.832    0.57   98.290    0.47
19         전북   99.904  0.07   99.975  ...   99.588    0.18   99.810    0.22
20         전남  101.642  0.28  101.996  ...  106.176    0.27  106.386    0.20
21         경북   98.536 -0.20   98.350  ...   95.900    0.32   96.130    0.24
22         경남   96.169 -0.51   95.757  ...   92.537    0.20   92.658    0.13
23         제주  100.737  0.20  100.784  ...   96.477   -0.10   96.393   -0.09

[24 rows x 51 columns]

# 데이터 컬럼명 변경

In [ ]:
df1.columns = ["지역 범위", "2018년 09월 지수", "2018년 09월 변동률", "2018년 10월 지수", "2018년 10월 변동률", "2018년 11월 지수", "2018년 11월 변동률", "2018년 12월 지수", "2018년 12월 변동률", "2019년 01월 지수", "2019년 01월 변동률", "2019년 02월 지수", "2019년 02월 변동률", "2019년 03월 지수", "2019년 03월 변동률", "2019년 04월 지수", "2019년 04월 변동률", "2019년 05월 지수", "2019년 05월 변동률", "2019년 06월 지수", "2019년 06월 변동률", "2019년 07월 지수", "2019년 07월 변동률", "2019년 08월 지수", "2019년 08월 변동률", "2019년 09월 지수", "2019년 09월 변동률", "2019년 10월 지수", "2019년 10월 변동률", "2019년 11월 지수", "2019년 11월 변동률", "2019년 12월 지수", "2019년 12월 변동률", "2020년 01월 지수", "2020년 01월 변동률", "2020년 02월 지수", "2020년 02월 변동률", "2020년 03월 지수", "2020년 03월 변동률", "2020년 04월 지수", "2020년 04월 변동률", "2020년 05월 지수", "2020년 05월 변동률", "2020년 06월 지수", "2020년 06월 변동률", "2020년 07월 지수", "2020년 07월 변동률", "2020년 08월 지수", "2020년 08월 변동률", "2020년 09월 지수", "2020년 09월 변동률"]
df1

    지역 범위  2018년 09월 지수  ...  2020년 09월 지수  2020년 09월 변동률
0      전국       100.902  ...       104.420           0.42
1     수도권       102.818  ...       109.200           0.43
2     지방권        99.197  ...       100.254           0.41
3   6대광역시       100.013  ...       104.705           0.53
4   5대광역시       100.040  ...       104.038           0.62
5     9개도        99.718  ...       102.105           0.38
6     8개도        98.600  ...        97.236           0.21
7      서울       106.048  ...       110.419           0.27
8      경기       101.208  ...       108.743           0.60
9      인천        99.922  ...       106.975           0.21
10     부산        98.897  ...        99.063           0.55
11     대구       102.275  ...       107.566           0.72
12     광주       102.403  ...       105.073           0.10
13     대전       100.902  ...       120.997           1.19
14     울산        95.288  ...        93.094           0.61
15     세종       101.728  ...       134.368           3.83
16     강원        99.068  ...        96.488           0.20
17     충북        98.195  ...        96.849           0.06
18     충남        98.515  ...        98.290           0.47
19     전북        99.904  ...        99.810           0.22
20     전남       101.642  ...       106.386           0.20
21     경북        98.536  ...        96.130           0.24
22     경남        96.169  ...        92.658           0.13
23     제주       100.737  ...        96.393          -0.09

[24 rows x 51 columns]

# 2018년도 데이터

In [ ]:
df2018 = df1.loc[0:6, ['지역 범위', '2018년 09월 지수', '2018년 09월 변동률', '2018년 10월 지수', '2018년 10월 변동률', '2018년 11월 지수', '2018년 11월 변동률', '2018년 12월 지수', '2018년 12월 변동률']]  # 2018년도
df2018

   지역 범위  2018년 09월 지수  ...  2018년 12월 지수  2018년 12월 변동률
0     전국       100.902  ...       101.216          -0.01
1    수도권       102.818  ...       103.574           0.07
2    지방권        99.197  ...        99.125          -0.08
3  6대광역시       100.013  ...       100.488           0.13
4  5대광역시       100.040  ...       100.426           0.07
5    9개도        99.718  ...        99.804          -0.09
6    8개도        98.600  ...        98.221          -0.17

[7 rows x 9 columns]

In [ ]:
내림차순2018 = df2018.sort_values(by=['2018년 09월 변동률', '2018년 10월 변동률', '2018년 11월 변동률', '2018년 12월 변동률'], ascending=False) # 2018년도 변동률 높은 순 정렬
내림차순2018

   지역 범위  2018년 09월 지수  ...  2018년 12월 지수  2018년 12월 변동률
1    수도권       102.818  ...       103.574           0.07
0     전국       100.902  ...       101.216          -0.01
5    9개도        99.718  ...        99.804          -0.09
4  5대광역시       100.040  ...       100.426           0.07
3  6대광역시       100.013  ...       100.488           0.13
2    지방권        99.197  ...        99.125          -0.08
6    8개도        98.600  ...        98.221          -0.17

[7 rows x 9 columns]

In [ ]:
df2018.T

                     0        1       2        3        4       5       6
지역 범위               전국      수도권     지방권    6대광역시    5대광역시     9개도     8개도
2018년 09월 지수   100.902  102.818  99.197  100.013   100.04  99.718    98.6
2018년 09월 변동률     0.31      0.7   -0.04     0.07     0.09    0.13   -0.13
2018년 10월 지수   101.094  103.247  99.181  100.188   100.22  99.812  98.453
2018년 10월 변동률     0.19     0.42   -0.02     0.17     0.18    0.09   -0.15
2018년 11월 지수   101.222    103.5    99.2  100.361  100.357  99.889  98.391
2018년 11월 변동률     0.13     0.25    0.02     0.17     0.14    0.08   -0.06
2018년 12월 지수   101.216  103.574  99.125  100.488  100.426  99.804  98.221
2018년 12월 변동률    -0.01     0.07   -0.08     0.13     0.07   -0.09   -0.17

# 2019년도 데이터

In [ ]:
df2019 = df1.loc[0:6, ['지역 범위', '2019년 01월 지수', '2019년 01월 변동률', '2019년 02월 지수', '2019년 02월 변동률', '2019년 03월 지수', '2019년 03월 변동률', '2019년 04월 지수', '2019년 04월 변동률', '2019년 05월 지수', '2019년 05월 변동률', '2019년 06월 지수', '2019년 06월 변동률', '2019년 07월 지수', '2019년 07월 변동률', '2019년 08월 지수', '2019년 08월 변동률', '2019년 09월 지수', '2019년 09월 변동률', '2019년 10월 지수', '2019년 10월 변동률', '2019년 11월 지수', '2019년 11월 변동률', '2019년 12월 지수', '2019년 12월 변동률']]  # 2019년도
df2019

   지역 범위  2019년 01월 지수  ...  2019년 12월 지수  2019년 12월 변동률
0     전국       101.067  ...       100.855           0.38
1    수도권       103.423  ...       104.042           0.62
2    지방권        98.978  ...        98.049           0.16
3  6대광역시       100.441  ...       100.987           0.45
4  5대광역시       100.376  ...       100.903           0.46
5    9개도        99.625  ...        98.553           0.19
6    8개도        98.007  ...        96.157          -0.04

[7 rows x 25 columns]

In [ ]:
내림차순2019 = df2019.sort_values(by=['2019년 01월 변동률', '2019년 02월 변동률', '2019년 03월 변동률', '2019년 04월 변동률', '2019년 05월 변동률', '2019년 06월 변동률', '2019년 07월 변동률', '2019년 08월 변동률', '2019년 09월 변동률', '2019년 10월 변동률', '2019년 11월 변동률', '2019년 12월 변동률'] , ascending=False) # 2019년도 변동률 높은 순 정렬
내림차순2019

   지역 범위  2019년 01월 지수  ...  2019년 12월 지수  2019년 12월 변동률
3  6대광역시       100.441  ...       100.987           0.45
4  5대광역시       100.376  ...       100.903           0.46
2    지방권        98.978  ...        98.049           0.16
0     전국       101.067  ...       100.855           0.38
1    수도권       103.423  ...       104.042           0.62
5    9개도        99.625  ...        98.553           0.19
6    8개도        98.007  ...        96.157          -0.04

[7 rows x 25 columns]

In [ ]:
df2019.T

                     0        1       2        3        4       5       6
지역 범위               전국      수도권     지방권    6대광역시    5대광역시     9개도     8개도
2019년 01월 지수   101.067  103.423  98.978  100.441  100.376  99.625  98.007
2019년 01월 변동률    -0.15    -0.15   -0.15    -0.05    -0.05   -0.18   -0.22
2019년 02월 지수   100.949  103.286  98.877  100.398  100.336  99.495  97.867
2019년 02월 변동률    -0.12    -0.13    -0.1    -0.04    -0.04   -0.13   -0.14
2019년 03월 지수   100.788  103.103  98.734  100.321  100.252  99.315  97.686
2019년 03월 변동률    -0.16    -0.18   -0.14    -0.08    -0.08   -0.18   -0.18
2019년 04월 지수   100.579  102.864  98.552  100.208   100.12   99.06  97.481
2019년 04월 변동률    -0.21    -0.23   -0.18    -0.11    -0.13   -0.26   -0.21
2019년 05월 지수   100.418  102.689  98.404  100.135  100.037  98.844  97.295
2019년 05월 변동률    -0.16    -0.17   -0.15    -0.07    -0.08   -0.22   -0.19
2019년 06월 지수    100.29  102.585  98.253  100.083   99.969  98.657  97.097
2019년 06월 변동률    -0.13     -0.1   -0.15    -0.05    -0.07   -0.19    -0.2
2019년 07월 지수   100.199   102.57  98.097  100.024   99.904  98.504  96.884
2019년 07월 변동률    -0.09    -0.02   -0.16    -0.06    -0.06   -0.15   -0.22
2019년 08월 지수    100.15  102.615  97.966  100.018   99.927  98.378  96.654
2019년 08월 변동률    -0.05     0.04   -0.13    -0.01     0.02   -0.13   -0.24
2019년 09월 지수   100.164  102.757   97.87  100.109   99.998  98.309  96.451
2019년 09월 변동률     0.01     0.14    -0.1     0.09     0.07   -0.07   -0.21
2019년 10월 지수   100.282  103.038  97.847   100.28  100.176    98.3  96.298
2019년 10월 변동률     0.12     0.27   -0.02     0.17     0.18   -0.01   -0.16
2019년 11월 지수   100.473  103.401  97.889  100.539  100.445  98.363  96.198
2019년 11월 변동률     0.19     0.35    0.04     0.26     0.27    0.06    -0.1
2019년 12월 지수   100.855  104.042  98.049  100.987  100.903  98.553  96.157
2019년 12월 변동률     0.38     0.62    0.16     0.45     0.46    0.19   -0.04

# 2020년도 데이터

In [ ]:
df2020 = df1.loc[0:6, ['지역 범위', '2020년 01월 지수', '2020년 01월 변동률', '2020년 02월 지수', '2020년 02월 변동률', '2020년 03월 지수', '2020년 03월 변동률', '2020년 04월 지수', '2020년 04월 변동률', '2020년 05월 지수', '2020년 05월 변동률', '2020년 06월 지수', '2020년 06월 변동률', '2020년 07월 지수', '2020년 07월 변동률', '2020년 08월 지수', '2020년 08월 변동률', '2020년 09월 지수', '2020년 09월 변동률']]  # 2020년도
df2020

   지역 범위  2020년 01월 지수  ...  2020년 09월 지수  2020년 09월 변동률
0     전국       101.133  ...       104.420           0.42
1    수도권       104.452  ...       109.200           0.43
2    지방권        98.212  ...       100.254           0.41
3  6대광역시       101.339  ...       104.705           0.53
4  5대광역시       101.300  ...       104.038           0.62
5    9개도        98.753  ...       102.105           0.38
6    8개도        96.141  ...        97.236           0.21

[7 rows x 19 columns]

In [ ]:
내림차순2020 = df2020.sort_values(by=['2020년 01월 변동률', '2020년 02월 변동률', '2020년 03월 변동률', '2020년 04월 변동률', '2020년 05월 변동률', '2020년 06월 변동률', '2020년 07월 변동률', '2020년 08월 변동률', '2020년 09월 변동률'] , ascending=False) # 2020년도 변동률 높은 순 정렬
내림차순2020

   지역 범위  2020년 01월 지수  ...  2020년 09월 지수  2020년 09월 변동률
1    수도권       104.452  ...       109.200           0.43
4  5대광역시       101.300  ...       104.038           0.62
3  6대광역시       101.339  ...       104.705           0.53
0     전국       101.133  ...       104.420           0.42
5    9개도        98.753  ...       102.105           0.38
2    지방권        98.212  ...       100.254           0.41
6    8개도        96.141  ...        97.236           0.21

[7 rows x 19 columns]

In [ ]:
df2020.T

                     0        1        2        3        4        5       6
지역 범위               전국      수도권      지방권    6대광역시    5대광역시      9개도     8개도
2020년 01월 지수   101.133  104.452   98.212  101.339    101.3   98.753  96.141
2020년 01월 변동률     0.28     0.39     0.17     0.35     0.39      0.2   -0.02
2020년 02월 지수   101.474  104.984   98.389   101.69  101.628   99.118  96.188
2020년 02월 변동률     0.34     0.51     0.18     0.35     0.32     0.37    0.05
2020년 03월 지수   102.024  105.957   98.577  102.269  101.893   99.724  96.245
2020년 03월 변동률     0.54     0.93     0.19     0.57     0.26     0.61    0.06
2020년 04월 지수   102.301    106.5   98.629  102.595  101.996  100.048  96.235
2020년 04월 변동률     0.27     0.51     0.05     0.32      0.1     0.32   -0.01
2020년 05월 지수    102.44  106.767   98.658  102.784  102.061  100.225  96.236
2020년 05월 변동률     0.14     0.25     0.03     0.18     0.06     0.18       0
2020년 06월 지수    102.86  107.295   98.987  103.291  102.481  100.663  96.471
2020년 06월 변동률     0.41     0.49     0.33     0.49     0.41     0.44    0.24
2020년 07월 지수   103.491  108.163   99.418  103.756  102.938   101.27  96.783
2020년 07월 변동률     0.61     0.81     0.44     0.45     0.45      0.6    0.32
2020년 08월 지수    103.98   108.73   99.841  104.156  103.396   101.72  97.035
2020년 08월 변동률     0.47     0.52     0.43     0.38     0.44     0.44    0.26
2020년 09월 지수    104.42    109.2  100.254  104.705  104.038  102.105  97.236
2020년 09월 변동률     0.42     0.43     0.41     0.53     0.62     0.38    0.21